before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Yn5ZBpBW+GqRjZi4XXdE4E3iXb6wXfXe8uYeLA/XjmRrFognU1ufpnX0hUVRBtoDBJQRVLWLuPVjV6clZL0qNe+RNOVZ1bnc0J7jTmZHK8CkMrYRabrEul+44qtY/wuqzbYnpiF7129ReIORiqH29Czhtlu/um5M+/61dWWe060TVdLqpiCCtyNwdLlc3k8LgpNCLkK/J238c8UW6GFxsuv3ixXft9jbdC8fQsn5n2VG7iDXs25qmJC1NI224HYQ0t4uqXqYm7dAYG/joPEfFZcHPy8NR2+PZOZxYGJrEGWBhE78WWUxWlLO90YsPBP9p9Qgd2WS87VGSssbyiuGNiRMRWBKMXb0zUncJzJh4lkkGBglMe2vF2rGaQkWwywOjaNaYOJA4oPEM5Z+C04RKsEoLuGIoiWp+9/pRssnb2vvTg4AocSvyEOekGG7i9oE6D848GrdhzQb0l7L3O3itDC/Td8VSQtxp+KlL+unIfYl8G4x0zJLkLGzYD7qp1ZP0u54CaYTXivAbGvritL4DjaQpK0xG2M+vzTo9Ltp7u2WDHwslHg2KbVENyZpQygX+OpFl0jFJIA+wXDhuytQyAn6SNcLU75bn0wwbi3xy0LyLsoqa8vwbRNq3QHKT2UuNFcf/dsWKAalAt9IInj08qbBz+E7P2KxMyi0EekMOUk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
